"""AST node classes for the PL/I interpreter.

Every node gets a `kind` class attribute (used for interpreter dispatch)
and positional fields.  Nodes are generated by the _mk factory to keep
this file short.
"""


class Node:
    kind = "Node"
    _fields = ()

    def __init__(self, *args, lineno=0):
        if len(args) != len(self._fields):
            raise TypeError("%s expects %d args, got %d"
                            % (self.kind, len(self._fields), len(args)))
        for name, val in zip(self._fields, args):
            setattr(self, name, val)
        self.lineno = lineno

    def __repr__(self):
        inner = ", ".join("%s=%r" % (f, getattr(self, f)) for f in self._fields)
        return "%s(%s)" % (self.kind, inner)


def _mk(kind, *fields):
    return type(kind, (Node,), {"kind": kind, "_fields": fields})


# ---- expressions -----------------------------------------------------
Num = _mk("Num", "value")                 # numeric constant
Str = _mk("Str", "value")                 # character constant
Bits = _mk("Bits", "value")               # bit-string constant '101'B
Ref = _mk("Ref", "name", "args")          # NAME or NAME(args): variable,
                                          # array element, function call,
                                          # builtin, or pseudo-variable
Member = _mk("Member", "base", "name", "args")   # qualified ref: base.NAME(args)
PtrRef = _mk("PtrRef", "base", "name", "args")   # pointer-qualified: P->X(args)
BinOp = _mk("BinOp", "op", "left", "right")
UnOp = _mk("UnOp", "op", "operand")

# ---- statements ------------------------------------------------------
Labeled = _mk("Labeled", "name", "stmt")
Assign = _mk("Assign", "target", "value")   # target: Ref or [Ref,...]
                                            # (multiple assignment)
CallStmt = _mk("CallStmt", "name", "args", "opts")  # opts: [(NAME, expr)]
If = _mk("If", "cond", "then", "els")               # els may be None
Block = _mk("Block", "body")                        # plain DO; ... END;
DoWhile = _mk("DoWhile", "conds", "body")           # conds: [(kw, expr), ...]
DoIter = _mk("DoIter", "var", "specs", "body")      # specs: [DoSpec, ...]
DoSpec = _mk("DoSpec", "start", "to", "by", "conds")
Select = _mk("Select", "subject", "whens", "otherwise")  # whens: [(exprs, stmt)]
Declare = _mk("Declare", "items")                   # items: [DeclItem, ...]
DeclItem = _mk("DeclItem", "names", "dims", "attrs", "level")  # level None = scalar
On = _mk("On", "cond", "qual", "unit")              # unit None = SYSTEM
SignalStmt = _mk("SignalStmt", "cond", "qual")
RevertStmt = _mk("RevertStmt", "cond", "qual")
Prefix = _mk("Prefix", "names", "stmt")             # (SIZE): condition prefix
AllocStmt = _mk("AllocStmt", "items")               # items: [(name, set_ref)]
FreeStmt = _mk("FreeStmt", "names")
IOStmt = _mk("IOStmt", "verb", "opts")  # OPEN/CLOSE/READ/WRITE/REWRITE/DELETE
                                        # opts: [(NAME, expr-or-None), ...]
WaitStmt = _mk("WaitStmt", "refs", "count")
ExecSql = _mk("ExecSql", "text")        # EXEC SQL ... ; (opaque SQL text)
Display = _mk("Display", "value", "reply")  # DISPLAY(e) [REPLY(ref)]
Put = _mk("Put", "clauses")     # clauses: [("PAGE",)|("SKIP",n)|("LIST",items)
                                #           |("EDIT",items,formats)]
Get = _mk("Get", "clauses")     # clauses: [("SKIP",n)|("LIST",refs)]
Goto = _mk("Goto", "label")
Return = _mk("Return", "value")                     # value may be None
Stop = _mk("Stop")
Null = _mk("Null")
Leave = _mk("Leave", "label")                       # label may be None
Iterate = _mk("Iterate", "label")
ProcDef = _mk("ProcDef", "params", "returns", "options", "recursive", "body")
BeginBlock = _mk("BeginBlock", "body")
FormatItem = _mk("FormatItem", "name", "args")      # A, F(8,2), X(3), SKIP...
FormatStmt = _mk("FormatStmt", "items")             # label: FORMAT(...);
