import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.ArrayDeque;

/**
 * Runtime support for Java code generated by pli/javagen.py.
 *
 * Scalars are represented as 1-element arrays (long[1]/double[1]/String[1])
 * so that CALL-by-reference works exactly like plain Java array aliasing;
 * PL/I arrays map directly to Java arrays (already reference types).
 * BIT strings are plain Strings of '0'/'1' characters.
 */
public final class PLI {
    private PLI() {}

    // ---- SYSPRINT-style output with 24-column PUT LIST tab stops ----

    private static final PrintStream OUT = System.out;
    private static final int LIST_TABS = 24;
    private static int column = 0;

    private static void write(String s) {
        OUT.print(s);
        int nl = s.lastIndexOf('\n');
        if (nl >= 0) column = s.length() - nl - 1;
        else column += s.length();
    }

    public static void putList(Object... vals) {
        for (Object v : vals) {
            String text = fmt(v);
            if (column > 0) write(" ".repeat(LIST_TABS - (column % LIST_TABS)));
            write(text);
        }
    }

    /** Called once at program end, mirroring the Python interpreter's
     *  final _flush_line(): ensures output ends with a newline. */
    public static void flushLine() {
        if (column > 0) write("\n");
    }

    public static void skip() { write("\n"); }

    public static void skip(long n) {
        for (long i = 0; i < Math.max(1, n); i++) write("\n");
    }

    private static String fmt(Object v) {
        if (v instanceof String) return (String) v;
        if (v instanceof Boolean) return ((Boolean) v) ? "'1'B" : "'0'B";
        if (v instanceof Double || v instanceof Float) return fmtNum(((Number) v).doubleValue());
        return String.valueOf(v);
    }

    private static String fmtNum(double v) {
        if (v == Math.rint(v) && Math.abs(v) < 1e15) return String.valueOf((long) v);
        return String.valueOf(v);
    }

    // ---- PUT EDIT format items: A, A(w), F(w), F(w,d), X(n) ----

    public static void editA(String v) { write(v); }

    public static void editA(String v, long w) {
        int n = (int) w;
        write(v.length() >= n ? v.substring(0, n) : v + " ".repeat(n - v.length()));
    }

    public static void editF(double v) { write(fmtNum(v)); }

    public static void editF(double v, long w) { write(rjust(fmtNum(v), (int) w)); }

    public static void editF(double v, long w, long d) {
        write(rjust(String.format(java.util.Locale.ROOT, "%." + d + "f", v),
                   (int) w));
    }

    public static void editX(long n) { write(" ".repeat((int) n)); }

    private static String rjust(String s, int w) {
        return s.length() >= w ? s : " ".repeat(w - s.length()) + s;
    }

    // ---- GET LIST: whitespace/comma-separated tokens from stdin ----

    private static final BufferedReader IN =
        new BufferedReader(new InputStreamReader(System.in));
    private static final ArrayDeque<String> tokens = new ArrayDeque<>();

    private static String nextToken() {
        while (tokens.isEmpty()) {
            String line;
            try {
                line = IN.readLine();
            } catch (IOException e) {
                throw new PLIError("ENDFILE", "I/O error reading SYSIN: " + e);
            }
            if (line == null) throw new PLIError("ENDFILE", "end of input file on GET");
            for (String t : line.replace(',', ' ').trim().split("\\s+")) {
                if (!t.isEmpty()) tokens.add(t);
            }
        }
        return tokens.poll();
    }

    public static long getLong() { return Long.parseLong(nextToken()); }
    public static double getDouble() { return Double.parseDouble(nextToken()); }
    public static String getString() { return nextToken(); }

    // ---- conditions ----

    /** Unhandled PL/I condition; the generated main() lets this terminate
     *  the program with a message, matching an unhandled ON-condition. */
    public static final class PLIError extends RuntimeException {
        public final String condition;
        public PLIError(String condition, String msg) {
            super(condition + ": " + msg);
            this.condition = condition;
        }
    }

    public static long zdiv(long a, long b) {
        if (b == 0) throw new PLIError("ZERODIVIDE", "division by zero");
        return a / b;
    }

    public static double zdiv(double a, double b) {
        if (b == 0) throw new PLIError("ZERODIVIDE", "division by zero");
        return a / b;
    }

    // ---- string / char builtins ----

    public static String substr(String s, long i, long len) {
        int start = (int) i - 1;
        int n = (int) len;
        if (start < 0 || n < 0 || start + n > s.length())
            throw new PLIError("STRINGRANGE",
                "SUBSTR(" + s + "," + i + "," + len + ") out of range");
        return s.substring(start, start + n);
    }

    public static String substr(String s, long i) {
        return substr(s, i, s.length() - i + 1);
    }

    /** SUBSTR(s, i, len) = value  pseudo-variable, returns the updated string. */
    public static String substrAssign(String s, long i, long len, String value) {
        int start = (int) i - 1;
        int n = (int) len;
        String v = value.length() >= n ? value.substring(0, n)
                                       : value + " ".repeat(n - value.length());
        return s.substring(0, start) + v + s.substring(start + n);
    }

    public static long length(String s) { return s.length(); }

    public static long index(String s, String t) { return s.indexOf(t) + 1; }

    public static String trim(String s) { return s.strip(); }

    public static String upper(String s) { return s.toUpperCase(); }

    public static String lower(String s) { return s.toLowerCase(); }

    /** COPY(s, n): n copies. */
    public static String repeatStr(String s, long n) { return s.repeat((int) Math.max(0, n)); }

    /** REPEAT(s, n): n+1 copies (PL/I semantics: 0 means "just s itself"). */
    public static String repeatPlus(String s, long n) {
        return s.repeat((int) Math.max(0, n) + 1);
    }

    public static long verify(String s, String allowed) {
        for (int i = 0; i < s.length(); i++)
            if (allowed.indexOf(s.charAt(i)) < 0) return i + 1;
        return 0;
    }

    public static String translate(String s, String to) { return s; }

    public static String translate(String s, String to, String from) {
        StringBuilder sb = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            int idx = from.indexOf(s.charAt(i));
            if (idx < 0) sb.append(s.charAt(i));
            else sb.append(idx < to.length() ? to.charAt(idx) : ' ');
        }
        return sb.toString();
    }

    /** CHAR(n): pad with blanks or truncate to a fixed width (non-VARYING assignment). */
    public static String charFixed(String s, long n) {
        int w = (int) n;
        return s.length() >= w ? s.substring(0, w) : s + " ".repeat(w - s.length());
    }

    /** PL/I character comparison pads the shorter operand with blanks. */
    public static boolean charEq(String a, String b) {
        int n = Math.max(a.length(), b.length());
        return charFixed(a, n).equals(charFixed(b, n));
    }

    public static int charCmp(String a, String b) {
        int n = Math.max(a.length(), b.length());
        return charFixed(a, n).compareTo(charFixed(b, n));
    }

    public static String concat(String a, String b) { return a + b; }

    // ---- bit strings (as '0'/'1' character Strings) ----

    public static boolean bitTrue(String bits) { return bits.indexOf('1') >= 0; }

    /** Wraps a bit string so PUT LIST displays it as 'text'B, matching
     *  the interpreter's PUT LIST formatting of BIT values. */
    public static final class Bits {
        private final String v;
        public Bits(String v) { this.v = v; }
        @Override public String toString() { return "'" + v + "'B"; }
    }

    public static Bits asBits(String s) { return new Bits(s); }

    public static String bitAnd(String a, String b) {
        int n = Math.max(a.length(), b.length());
        a = a.length() < n ? a + "0".repeat(n - a.length()) : a;
        b = b.length() < n ? b + "0".repeat(n - b.length()) : b;
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++)
            sb.append(a.charAt(i) == '1' && b.charAt(i) == '1' ? '1' : '0');
        return sb.toString();
    }

    public static String bitOr(String a, String b) {
        int n = Math.max(a.length(), b.length());
        a = a.length() < n ? a + "0".repeat(n - a.length()) : a;
        b = b.length() < n ? b + "0".repeat(n - b.length()) : b;
        StringBuilder sb = new StringBuilder(n);
        for (int i = 0; i < n; i++)
            sb.append(a.charAt(i) == '1' || b.charAt(i) == '1' ? '1' : '0');
        return sb.toString();
    }

    public static String bitNot(String a) {
        StringBuilder sb = new StringBuilder(a.length());
        for (int i = 0; i < a.length(); i++) sb.append(a.charAt(i) == '1' ? '0' : '1');
        return sb.toString();
    }

    // ---- arithmetic / numeric builtins ----

    public static long abs(long x) { return Math.abs(x); }
    public static double abs(double x) { return Math.abs(x); }

    /** PL/I MOD is floor-mod (result has the sign of the divisor). */
    public static long mod(long a, long b) {
        long r = a % b;
        return (r != 0 && ((r < 0) != (b < 0))) ? r + b : r;
    }

    public static long min(long a, long b) { return Math.min(a, b); }
    public static double min(double a, double b) { return Math.min(a, b); }
    public static long max(long a, long b) { return Math.max(a, b); }
    public static double max(double a, double b) { return Math.max(a, b); }

    public static double sqrt(double x) { return Math.sqrt(x); }
    public static long trunc(double x) { return (long) x; }
    public static long ceil(double x) { return (long) Math.ceil(x); }
    public static long floor(double x) { return (long) Math.floor(x); }
    public static long round(double x) { return Math.round(x); }

    public static long hbound(long[] a) { return a.length; }
    public static long hbound(double[] a) { return a.length; }
    public static long hbound(String[] a) { return a.length; }
}
